basic_config: ___redshift_common.yml
layer_setting:
    -   layer_name: LGT
        layer_setting:
            render_setting:
                ### output [tab]
                #       unified sampling [row layout]
                #           min samples:
                "redshiftOptions.unifiedMinSamples": 32
                #           max samples:
                "redshiftOptions.unifiedMaxSamples": 256
                #           adaptive error threshold:
                "redshiftOptions.unifiedAdaptiveErrorThreshold": 0.030
                ### AOV [tab]
                #       general [row layout]
                #           mode:
                "redshiftOptions.aovGlobalEnableMode": 0 #0,1
                ### GI [tab]
                #       general [row layout]
                #           primary gi engine:
                "redshiftOptions.primaryGIEngine": 4 #0,1,2,3,4   { 4: brute force }
                #           secondary gi engine:
                "redshiftOptions.secondaryGIEngine": 4 #  { 4: brute force }
                #       brute force gi [row layout]
                #           num rays:
                #"redshiftOptions.bruteForceGINumRays": 512
                ### System [tab]
                #       Material Override [row layout]
                #           enable:
                "redshiftOptions.materialOverrideEnable": 1 #0,1
