lr:
  dir: E:/huayu-storm/TTT/lr/{episode}/{sequence}/{shot}
  file: ttt_{episode}_{sequence}_{shot}_{layer}_{version}.mb
compositing:
  dir: E:/huayu-storm/TTT/compositing/{episode}/{sequence}/{shot}
  file: ttt_{episode}_{sequence}_{shot}_cp_{version}.%04d.{ext}
images:
  dir: E:/huayu-storm/TTT/images/{episode}/{sequence}/{shot}/{layer}
  file: dr_{episode}_{sequence}_{shot}_l3Color_lr_001_{layer}.%04d.exr
mov:
  dir: E:/huayu-storm/TTT/mov/{episode}/{sequence}/{shot}
  file: ttt_{episode}_{sequence}_{shot}_cp_{version}.mov
nuke:
  dir: E:/huayu-storm/TTT/nuke/{episode}/{sequence}/{shot}
  file: ttt_{episode}_{sequence}_{shot}_cp_{version}.nk
anim:
  dir: E:/huayu-storm/TTT/compositing/{episode}/{sequence}/{shot}
  file: ttt_{episode}_{sequence}_{shot}_an_{version}.mov
nuke_template:
  dir: E:/huayu-storm/TTT/nuke/nuke_moban/{episode}/{sequence}
  file: "{episode}_{sequence}.nk"