
export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS'

export const GET_PROJECT_LIST_FAILED = 'GET_PROJECT_LIST_FAILED'

export const GET_PROJECT_LIST_LOADING = 'GET_PROJECT_LIST_LOADING'