
export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS'

export const GET_PROJECT_LIST_FAILED = 'GET_PROJECT_LIST_FAILED'

export const GET_PROJECT_LIST_LOADING = 'GET_PROJECT_LIST_LOADING'

export const GET_SHOT_LIST_SUCCESS = 'GET_SHOT_LIST_SUCCESS'

export const GET_SHOT_LIST_FAILED = 'GET_SHOT_LIST_FAILED'

export const GET_SHOT_LIST_LOADING = 'GET_SHOT_LIST_LOADING'

export const OVERVIEW_PROJECT_FILTERS = 'OVERVIEW_PROJECT_FILTERS'

export const OVERVIEW_SHOT_FILTERS = 'OVERVIEW_SHOT_FILTERS'

export const MAYABATCH_FILTERS = 'MAYABATCH_FILTERS'

export const MAYABATCH_ITEMS = 'MAYABATCH_ITEMS'

export const NUKEBATCH_PROJECT_FILTERS = 'NUKEBATCH_PROJECT_FILTERS'

export const NUKEBATCH_SHOT_FILTERS = 'NUKEBATCH_SHOT_FILTERS'

export const NUKEBATCH_TASKID = 'NUKEBATCH_TASKID'

export const NUKEBATCH_ITEMS = 'NUKEBATCH_ITEMS'

export const SEQ2MOVBATCH_FILTERS = 'SEQ2MOVBATCH_FILTERS'

export const SEQ2MOVBATCH_ITEMS = 'SEQ2MOVBATCH_ITEMS'