
export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS'

export const GET_PROJECT_LIST_FAILED = 'GET_PROJECT_LIST_FAILED'

export const GET_PROJECT_LIST_LOADING = 'GET_PROJECT_LIST_LOADING'

export const OVERVIEW_FILTERS = 'OVERVIEW_FILTERS'

export const MAYABATCH_FILTERS = 'MAYABATCH_FILTERS'

export const NUKEBATCH_FILTERS = 'NUKEBATCH_FILTERS'

export const NUKEBATCH_TASKID = 'NUKEBATCH_TASKID'

export const SEQ2MOVBATCH_FILTERS = 'SEQ2MOVBATCH_FILTERS'